app:
  name: "My Fancy Go App"
  debug: true
  env: "development"
  banner_path: "banner.txt"

server:
  port: "8080"

services:
  enable_service_a: true
  enable_service_b: false
  enable_service_c: true
  enable_service_d: true

auth:
  type: "apikey"
  secret: "super-secret-key"

redis:
  enabled: false
  address: "localhost:6379"
  password: ""
  db: 0

kafka:
  enabled: false
  brokers: 
    - "localhost:9092"
  topic: "my-topic"
  group_id: "my-group"

postgres:
  enabled: false
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "mydb"
  sslmode: "disable"
