app:
  name: "My Fancy Go App"
  debug: true
  env: "development"
  banner_path: "banner.txt"

server:
  port: "8080"

services:
  enable_service_a: true
  enable_service_b: false
  enable_service_c: true

auth:
  type: "apikey"
  secret: "super-secret-key"
